[[headers]]
  for = "/*"
    [headers.values]
      Access-Control-Allow-Origin = "*"
    
[[headers]]
  for = "/logos/*"
    [headers.values]
    Cache-Control = "public, immutable, max-age=31536000"
